Fixed

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -1,27 +1,28 @@
-name: "Vprofile IAC"
-on: 
-  push: 
-    branches: 
+name: Terraform Workflow
+
+on:
+  push:
+    branches:
       - main
       - stage
-    paths: 
-      - terraform/**
+    paths:
+      - 'terraform/**'
   pull_request:
     branches:
       - main
-    paths: 
-      - terraform/**
+    paths:
+      - 'terraform/**'
 
-env: 
-AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE}}
-AWS_REGION: us-east-2
-EKS_CLUSTER: vprofile-eks
+env:
+  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+  BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}
+  AWS_REGION: us-east-2
+  EKS_CLUSTER: vprofile-eks
 
 jobs:
   terraform:
-    name: "Apply terraform code changes"
+    name: "Apply Terraform Changes"
     runs-on: ubuntu-latest
     defaults:
       run:
@@ -32,31 +33,22 @@ jobs:
       - name: Checkout source code
         uses: actions/checkout@v4
         
-      - name: setup Terraform
+      - name: Setup Terraform
         uses: hashicorp/setup-terraform@v2
-        #with: 
-        #  terraform_version: 1.6.3
+        #with:
+          #terraform_version: 1.6.3
 
-      - name: Terraform init
-        id: init
-        run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"
-        
-      - name: Terraform format
-        id: fmt
+      - name: Terraform Init
+        run: terraform init -backend-config="bucket=${BUCKET_TF_STATE}"
+
+      - name: Terraform Format Check
         run: terraform fmt -check
         
-      - name: Terraform validate
-        id: validate
+      - name: Terraform Validate
         run: terraform validate
 
-      - name: Terraform plan
+      - name: Terraform Plan
         id: plan
-        run: terraform plan -no-color -input=false -out planfile
-        continue-on-error: true
+        run: terraform plan -no-color -input=false -out=planfile || echo "Terraform Plan Failed!"
 
-      - name: Terraform plan status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
-
-
-    
+      
